# Generated by Django 4.1 on 2022-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dash_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15)),
                ('item_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_price',
        ),
    ]
