# Generated by Django 4.1 on 2022-09-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_dash_dates_remove_dashboard_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash_dates',
            name='qaysinga',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.dashboard'),
            preserve_default=False,
        ),
    ]
