# Generated by Django 4.1 on 2022-09-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_dash_dates_qaysinga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash_dates',
            name='qaysinga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dashboard'),
        ),
    ]
