# Generated by Django 4.1 on 2022-09-03 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_dash_dates_qaysinga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
