# Generated by Django 4.1 on 2022-09-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_comment_email_alter_comment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
