# Generated by Django 4.1.2 on 2022-10-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lyrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lyrics',
        ),
    ]
