# Generated by Django 4.1.2 on 2022-10-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_addelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addelement',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoshish', to='dashboard.dashboard'),
        ),
    ]
