# Generated by Django 4.1.2 on 2022-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_addelement_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='addelement',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
