# Generated by Django 4.1.2 on 2022-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_addelement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addelement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
