# Generated by Django 4.1.2 on 2022-10-29 14:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_addelement_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(unique=True, verbose_name=dashboard.models.MyUser),
        ),
    ]
