# Generated by Django 4.1.2 on 2022-10-29 14:09

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_dashboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(unique=True, verbose_name=dashboard.models.MyUser),
        ),
    ]
