# Generated by Django 4.1.2 on 2022-10-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_dashboard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='descraption',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
