# Generated by Django 4.1.2 on 2022-11-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_dashboard_active_alter_dashboard_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='active',
        ),
    ]
