# Generated by Django 4.1.2 on 2022-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_dashboard_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
