# Generated by Django 4.1.2 on 2022-11-04 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_chart_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='descraption',
            new_name='caption',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='arrivals5.png', upload_to='profile')),
                ('bio', models.CharField(blank=True, default='bio', max_length=100, null=True)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
