# Generated by Django 4.1.2 on 2022-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='heaven_to_heaven.jpg', upload_to='profile'),
        ),
    ]
