# Generated by Django 4.1.2 on 2022-11-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='element',
            name='active',
        ),
    ]
