# Generated by Django 4.1.2 on 2022-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_remove_chart_active_remove_element_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
