# Generated by Django 4.1.2 on 2022-11-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
