# Generated by Django 4.1.2 on 2022-11-12 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_element_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='created_on',
        ),
        migrations.AddField(
            model_name='chart',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
