# Generated by Django 4.1.2 on 2022-11-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0015_chart_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Taklif', 'Taklif'), ('Shikoyat', 'Shikoyat')], default='Taklif', max_length=8)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
