# Generated by Django 4.1.2 on 2022-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0016_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
