# Generated by Django 4.1.2 on 2022-11-13 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0017_contactus_is_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart', to=settings.AUTH_USER_MODEL),
        ),
    ]
