# Generated by Django 4.1.2 on 2022-11-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0018_alter_chart_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='chart.chart'),
        ),
    ]
