# Generated by Django 4.1.2 on 2022-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0022_alter_chart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('Pie Chart', 'Pie Chart'), ('Column Chart', 'Column Chart')], default='Pie Chart', max_length=15),
        ),
    ]
