# Generated by Django 4.1.2 on 2022-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0024_alter_chart_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
