# Generated by Django 4.1.2 on 2022-12-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0027_profile_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verfy_account1', models.URLField(unique=True)),
                ('verfy_account2', models.URLField(unique=True)),
                ('message', models.TextField(max_length=700)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
