# Generated by Django 4.1.2 on 2022-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0030_alter_accountverify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverify',
            name='verfy_account1',
            field=models.URLField(),
        ),
    ]
