# Generated by Django 4.1.2 on 2022-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0031_alter_accountverify_verfy_account1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverify',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='accountverify',
            name='verfy_account1',
            field=models.URLField(unique=True),
        ),
    ]
