# Generated by Django 4.1.2 on 2022-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0032_alter_accountverify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverify',
            name='verfy_account2',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
