# Generated by Django 4.1.2 on 2022-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0033_accountverify_verfy_account2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountverify',
            name='verfy_account2',
        ),
    ]
