# Generated by Django 4.1.2 on 2022-12-09 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0034_remove_accountverify_verfy_account2'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverify',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
