# Generated by Django 4.1.2 on 2022-12-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0037_alter_accountverify_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountverify',
            old_name='username',
            new_name='request_username',
        ),
    ]
