# Generated by Django 4.1.2 on 2022-12-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0039_alter_accountverify_request_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
