# Generated by Django 4.1.2 on 2022-12-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0040_chart_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to='chart.chart'),
        ),
    ]
