# Generated by Django 4.1.2 on 2022-12-25 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0044_alter_chart_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='like',
            field=models.ManyToManyField(related_name='likee', to=settings.AUTH_USER_MODEL),
        ),
    ]
