# Generated by Django 4.1.2 on 2022-12-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0045_alter_chart_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='like',
        ),
        migrations.AddField(
            model_name='myuser',
            name='like',
            field=models.ManyToManyField(related_name='likee', to='chart.chart'),
        ),
    ]
